pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('Docker_Hub')
	}
    stages {
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Build & push Dockerfile') {
            steps {
                sh "cd laravel-app"
		    // Stop the running container if it exists
            sh '''
            docker stop laravel-container || true
            '''

            // Remove the stopped container
            sh '''
            docker rm laravel-container || true
            '''

            // Remove the old Docker image
            sh '''
            docker rmi bassam2080/laravel-app || true
            '''

            // Build the new Docker image
            sh '''
            docker build -t bassam2080/laravel-app .
            '''

            // Push the image to DockerHub
            sh '''
            docker push bassam2080/laravel-app
            '''
            }
        }
        stage('Run Dockercompose playbook') {
            steps {
                sh """
                cd laravel-app
                ansible-playbook playbook-dcompose.yml 
                """
            }
        }
    }
}
